name: Build and Deploy Payroll Server

# This workflow runs automatically every time you push to the 'main' branch
on:
  push:
    branches: [ master ]

# A workflow is made of one or more jobs that can run in parallel or sequentially
jobs:
  build-and-deploy:
    # This job runs on a fresh virtual machine provided by GitHub
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository's code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up the correct Java version (JDK 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Build the project with Maven, which creates our "fat JAR"
      - name: Build with Maven
        run: mvn clean package

      # Step 4: Securely copy the new JAR file to your AWS server
      - name: Copy JAR to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          source: "target/DCOMToSchool-1.0-SNAPSHOT.jar" # Path to the built JAR
          target: "/home/ubuntu/" # Destination on the server

      # Step 5: Execute commands on the AWS server to restart the application
      - name: Restart Server on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            # This command ensures that the script will exit immediately if any command fails.
            set -e
            
            echo "--- Stopping old server process (if any) ---"
            # The '|| true' part ensures this step doesn't fail if no process was found to kill.
            pkill -f 'java -jar DCOMToSchool-1.0-SNAPSHOT.jar' || echo "No old process to stop."
            sleep 2

            echo "--- Starting new server process in the background ---"
            cd /home/ubuntu
            # The command to start the server is the same.
            nohup java -jar DCOMToSchool-1.0-SNAPSHOT.jar ${{ secrets.AWS_HOST }} > server.log 2>&1 &
            
            # Wait for 10 seconds. This gives the Java application crucial time to initialize.
            echo "--- Waiting 10 seconds for server to initialize... ---"
            sleep 10
            
            # THE KEY FIX: Check the log file to confirm the server is actually running.
            echo "--- Verifying server status from log file ---"
            if grep -q "Payroll RMI Server is running and ready" server.log; then
              echo "✅ SUCCESS: Server started successfully and is ready."
            else
              echo "❌ FAILURE: Server startup message not found in log."
              echo "--- Displaying full server.log for debugging ---"
              cat server.log
              exit 1 # This will explicitly fail the GitHub Actions step.
            fi
